// Emoji keyword index for the picker's filter input.
//
// Each entry maps an emoji character to a list of searchable keywords:
// Chinese names, English equivalents, and pinyin prefixes. The filter
// matches if any keyword contains the query (case-insensitive) OR if the
// emoji character itself / its category name contains the query.
//
// Convention for keywords:
//   - Place the most likely search term first (it doesn't affect matching,
//     but keeps the table human-readable).
//   - Chinese first, then English, then pinyin without tones.
//   - Keep keywords short; users type 1-3 chars in this UI.
//
// This file is data-only — no runtime behavior beyond the export.

export const EMOJI_KEYWORDS: Record<string, string[]> = {
  // ===== 常用 =====
  '📝': ['备忘录', '笔记', '记录', '便签', 'memo', 'note', 'biwanglu', 'biji'],
  '📚': ['书', '书本', '阅读', '图书', 'books', 'shu', 'yuedu'],
  '💡': ['灯泡', '想法', '灵感', '提示', 'bulb', 'idea', 'dengpao', 'xiangfa'],
  '🎯': ['目标', '靶心', '焦点', 'target', 'dart', 'mubiao', 'baxin'],
  '🚀': ['火箭', '起飞', '发射', '启动', 'rocket', 'huojian', 'qifei'],
  '⭐': ['星', '星星', 'star', 'xing'],
  '🌟': ['星', '闪亮', '发光', 'star', 'shine', 'glowing', 'xing', 'shanliang'],
  '🔥': ['火', '火焰', '热门', '燃烧', 'fire', 'flame', 'huo', 're'],
  '💻': ['电脑', '笔记本', '计算机', 'laptop', 'computer', 'diannao'],
  '📊': ['图表', '柱状图', '数据', '统计', 'chart', 'bar', 'tubiao', 'shuju'],
  '🎨': ['调色板', '画板', '艺术', '美术', 'palette', 'art', 'tiaoseban', 'huaban'],
  '📌': ['图钉', '别针', '固定', 'pushpin', 'pin', 'tudin'],
  '✅': ['勾', '对', '完成', '确认', 'check', 'done', 'gou', 'dui', 'wancheng'],
  '❤️': ['心', '爱心', '红心', '喜欢', '爱', 'heart', 'love', 'xin', 'ai'],
  '😊': ['笑', '微笑', '开心', '高兴', 'smile', 'happy', 'xiao', 'weixiao', 'kaixin'],
  '🎉': ['庆祝', '派对', '聚会', '礼花', 'party', 'celebrate', 'qingzhu'],
  '👍': ['赞', '好', '点赞', 'thumbs', 'up', 'zan', 'hao', 'dianzan'],
  '💪': ['肌肉', '力量', '加油', '强壮', 'muscle', 'flex', 'jirou', 'jiayou'],
  '🎵': ['音符', '音乐', '歌', 'note', 'music', 'yinfu', 'yinyue', 'ge'],
  '🎁': ['礼物', '礼品', '赠送', 'gift', 'present', 'liwu'],
  '🏆': ['奖杯', '冠军', '胜利', 'trophy', 'win', 'jiangbei', 'guanjun'],
  '👋': ['挥手', '你好', '招呼', 'wave', 'hello', 'hi', 'huishou', 'nihao'],
  '🌸': ['樱花', '花', 'sakura', 'cherry', 'blossom', 'yinghua', 'hua'],
  '🌿': ['草', '草本', '绿叶', '植物', 'herb', 'cao', 'zhiwu'],
  '🌊': ['海浪', '浪', '波', 'wave', 'water', 'hailang', 'lang'],
  '☀️': ['太阳', '晴天', '阳光', 'sun', 'sunny', 'taiyang', 'qing'],
  '🌙': ['月亮', '夜晚', '月', 'moon', 'night', 'yueliang', 'ye'],
  '🌈': ['彩虹', '彩虹色', 'rainbow', 'caihong'],
  '🍀': ['四叶草', '幸运', '草', 'clover', 'luck', 'siyecao', 'xingyun'],
  '💎': ['钻石', '宝石', 'diamond', 'gem', 'zhuanshi', 'baoshi'],

  // ===== 表情 =====
  '😀': ['笑脸', '微笑', '开心', 'smile', 'happy', 'xiaolian', 'kaixin'],
  '😃': ['大笑', '高兴', 'smile', 'big', 'daxiao', 'gaoxin'],
  '😄': ['笑', '开心', 'smile', 'xiao', 'kaixin'],
  '😁': ['笑', '咧嘴', 'grin', 'xiao', 'liezui'],
  '😆': ['笑', '嘻嘻', 'laugh', 'xiao', 'xixi'],
  '😅': ['尴尬笑', '汗', 'sweat', 'smile', 'ganga', 'han'],
  '🤣': ['笑哭', '哈哈', 'rofl', 'roll', 'xiaoku', 'haha'],
  '😂': ['笑哭', '流泪', 'joy', 'tears', 'xiaoku', 'liulei'],
  '🙂': ['微笑', 'smile', 'weixiao'],
  '🙃': ['倒脸', '反讽', 'upside', 'daolian', 'fanfen'],
  '😉': ['眨眼', '调情', 'wink', 'zhayan'],
  '😇': ['天使', 'halo', 'angel', 'tianshi'],
  '🥰': ['爱心', '喜欢', 'hearts', 'love', 'aixin', 'xihuan'],
  '😍': ['眼爱心', '迷恋', 'heart', 'eyes', 'love', 'milian'],
  '🤩': ['眼冒星', '惊叹', 'star', 'struck', 'jingtan'],
  '😘': ['飞吻', 'kiss', 'feiwen'],
  '😗': ['亲吻', 'kissing', 'qinwen'],
  '😚': ['亲吻闭眼', 'kiss', 'qinwen'],
  '😙': ['亲吻微笑', 'kiss', 'qinwen'],
  '😋': ['好吃', '美味', '舔唇', 'yummy', 'haochi', 'meiwei'],
  '😛': ['吐舌', 'tongue', 'tushe'],
  '😜': ['眨眼吐舌', 'wink', 'tongue', 'tushe'],
  '🤪': ['疯狂', '傻', 'zany', 'crazy', 'fengkuang'],
  '😝': ['吐舌闭眼', 'tongue', 'tushe'],
  '🤑': ['钱嘴', '发财', 'money', 'mouth', 'qianzui', 'facai'],
  '🤗': ['拥抱', 'hug', 'hugging', 'yongbao'],
  '🤭': ['捂嘴', '偷笑', 'giggle', 'wuzui'],
  '🤫': ['嘘', '安静', 'shush', 'quiet', 'xu', 'anjing'],
  '🤔': ['思考', '想', 'think', 'hmm', 'sikao', 'xiang'],
  '😐': ['冷漠', '无表情', 'neutral', 'lengmo'],
  '😑': ['无表情', 'deadpan', 'wubiaoqing'],
  '😶': ['无嘴', '沉默', 'silent', 'mouthless', 'wuzui', 'chenmo'],
  '😏': ['得意', 'smirk', 'deyi'],
  '😒': ['不满', '无趣', 'unamused', 'buman'],
  '🙄': ['翻白眼', 'eye', 'roll', 'fanbaiyan'],
  '😬': ['做鬼脸', 'grimace', 'zuoguilian'],
  '😌': ['安心', 'relieved', 'anxin'],
  '😔': ['沮丧', 'pensive', 'juesang'],
  '😪': ['困', 'sleepy', 'kun'],
  '😴': ['睡觉', 'sleep', 'sleeping', 'shuijiao'],
  '😷': ['口罩', '生病', 'mask', 'sick', 'kouzhao', 'bingsen'],
  '🤒': ['温度计', '生病', 'thermometer', 'sick', 'shengbing'],
  '🤕': ['绷带', '受伤', 'bandage', 'hurt', 'shoushang'],
  '🤢': ['恶心', '绿脸', 'nauseated', 'green', 'exin'],
  '🤮': ['呕吐', 'vomit', 'outtu'],
  '🥵': ['热', '发烧', 'hot', 'heat', 're', 'fashao'],
  '🥶': ['冷', '冻', 'cold', 'freezing', 'leng'],
  '🥴': ['晕', '醉', 'woozy', 'drunk', 'yun', 'zui'],
  '😵': ['晕倒', '头晕', 'dizzy', 'yundao', 'toubun'],
  '🤯': ['爆炸', '震惊', 'mind', 'blown', 'exploding', 'zhenjing'],
  '🤠': ['牛仔', 'cowboy', 'niuzai'],
  '🥳': ['派对', '庆祝', 'party', 'celebrate', 'paidui'],
  '😎': ['酷', '墨镜', 'cool', 'sunglasses', 'mojing'],
  '🤓': ['书呆子', 'nerd', 'shudai'],
  '🧐': ['礼帽', '观察', 'monocle', 'guancha'],
  '😕': ['困惑', 'confused', 'kunhuo'],
  '😟': ['担心', 'worried', 'danxin'],
  '😮': ['惊讶', '张嘴', 'surprised', 'open', 'mouth', 'jingya'],
  '😯': ['抑制', 'hushed', 'yizhi'],
  '😲': ['astonished', '震惊', 'zhenjing'],
  '😳': ['脸红', 'flushed', 'lianhong'],
  '🥺': ['恳求', 'pleading', 'kenqiu'],
  '😢': ['哭', '伤心', 'cry', 'sad', 'shangxin'],
  '😭': ['大哭', '流泪', 'sob', 'cry', 'dacry', 'liulei'],
  '😱': ['尖叫', '恐惧', 'scream', 'fear', 'jianjiao'],
  '😖': ['困扰', 'confounded', 'kunrao'],
  '😣': ['坚持', 'persevere', 'jianchi'],
  '😞': ['失望', 'disappointed', 'shiwang'],
  '😓': ['冷汗', 'sweat', 'lenghan'],
  '😩': ['疲惫', 'weary', 'tanjuan'],
  '😫': ['累', 'tired', 'lei'],
  '😤': ['鼻息', 'triumph', 'bixi'],
  '😡': ['生气', 'pout', 'angry', 'shengqi'],
  '😠': ['愤怒', 'angry', 'fennu'],
  '🤬': ['诅咒', 'swear', 'zuzhou'],
  '😈': ['魔鬼笑', 'devil', 'horns', 'mogui'],
  '👿': ['小恶魔', 'devil', 'imp', 'emo'],
  '💀': ['骷髅', 'skull', 'kulou'],
  '💩': ['大便', 'shit', 'poo', 'dabian'],
  '🤡': ['小丑', 'clown', 'xiaochou'],
  '👹': ['食人魔', 'ogre', 'shirenmo'],
  '👺': ['天狗', 'goblin', 'tiangou'],
  '👻': ['鬼', '幽灵', 'ghost', 'gui', 'youling'],
  '👽': ['外星人', 'alien', 'waixingren'],
  '👾': ['怪物', 'alien', 'monster', 'guaiwu'],
  '🤖': ['机器人', 'robot', 'jiqiren'],

  // ===== 动物 =====
  '🐱': ['猫', 'cat', 'mao'],
  '🐶': ['狗', 'dog', 'gou'],
  '🐭': ['鼠', 'mouse', 'shu'],
  '🐹': ['仓鼠', 'hamster', 'cangshu'],
  '🐰': ['兔', 'rabbit', 'tu'],
  '🦊': ['狐狸', 'fox', 'huli'],
  '🐻': ['熊', 'bear', 'xiong'],
  '🐼': ['熊猫', 'panda', 'xiongmao'],
  '🐨': ['考拉', '树袋熊', 'koala', 'kaola'],
  '🐯': ['虎', 'tiger', 'hu'],
  '🦁': ['狮', 'lion', 'shi'],
  '🐮': ['牛', 'cow', 'niu'],
  '🐷': ['猪', 'pig', 'zhu'],
  '🐸': ['蛙', 'frog', 'wa'],
  '🐵': ['猴', 'monkey', 'hou'],
  '🐔': ['鸡', 'chicken', 'ji'],
  '🐧': ['企鹅', 'penguin', 'qie'],
  '🐦': ['鸟', 'bird', 'niao'],
  '🐤': ['小鸡', 'chick', 'xiaoji'],
  '🦄': ['独角兽', 'unicorn', 'dujiaoshou'],
  '🐝': ['蜜蜂', 'bee', 'mifeng'],
  '🐛': ['虫', 'bug', 'chong'],
  '🦋': ['蝴蝶', 'butterfly', 'hudie'],
  '🐌': ['蜗牛', 'snail', 'woniu'],
  '🐞': ['瓢虫', 'ladybug', 'piaochong'],
  '🐜': ['蚂蚁', 'ant', 'mayi'],
  '🦆': ['鸭', 'duck', 'ya'],
  '🦅': ['鹰', 'eagle', 'ying'],
  '🦉': ['猫头鹰', 'owl', 'maotouying'],
  '🦇': ['蝙蝠', 'bat', 'bianfu'],

  // ===== 自然 =====
  '🌸': ['樱花', 'sakura', 'yinghua'],
  '🌺': ['木槿', 'hibiscus', 'mujin'],
  '🌻': ['向日葵', 'sunflower', 'xiangrikui'],
  '🌹': ['玫瑰', 'rose', 'meigui'],
  '🌷': ['郁金香', 'tulip', 'yujinxiang'],
  '🌱': ['幼苗', 'sprout', 'yumiao'],
  '🌿': ['草本', 'herb', 'caoben'],
  '☘️': ['三叶草', 'shamrock', 'sanyecao'],
  '🍀': ['四叶草', 'clover', 'luck', 'siyecao', 'xingyun'],
  '🍁': ['枫叶', 'maple', 'fengye'],
  '🍂': ['落叶', 'fallen', 'leaf', 'luoye'],
  '🍃': ['叶子', 'wind', 'leaf', 'yezi'],
  '🌴': ['棕榈', 'palm', 'zonglv'],
  '🌵': ['仙人掌', 'cactus', 'xianrenzhang'],
  '🌾': ['稻穗', 'rice', 'daosui'],
  '🍄': ['蘑菇', 'mushroom', 'mogu'],
  '🌲': ['松树', 'evergreen', 'songshu'],
  '🌳': ['落叶树', 'tree', 'luoyeshu', 'shu'],
  '🔥': ['火', 'fire', 'huo'],
  '💧': ['水滴', 'droplet', 'shuidi'],
  '🌊': ['浪', 'wave', 'lang'],
  '☔': ['雨伞', 'umbrella', 'rain', 'yusan'],
  '❄️': ['雪', '雪花', 'snow', 'snowflake', 'xue'],
  '⛅': ['多云', 'cloud', 'duoyun'],
  '🌈': ['彩虹', 'rainbow', 'caihong'],
  '☀️': ['太阳', 'sun', 'taiyang'],
  '🌙': ['月亮', 'moon', 'yueliang'],
  '⭐': ['星', 'star', 'xing'],
  '💫': ['头晕', '星', 'dizzy', 'star', 'xing'],
  '🪐': ['行星', '土星', 'planet', 'saturn', 'xingxing'],

  // ===== 食物 =====
  '🍎': ['苹果', 'apple', 'pingguo'],
  '🍐': ['梨', 'pear', 'li'],
  '🍊': ['橘子', '橙子', 'orange', 'tangerine', 'juzi'],
  '🍋': ['柠檬', 'lemon', 'ningmeng'],
  '🍌': ['香蕉', 'banana', 'xiangjiao'],
  '🍉': ['西瓜', 'watermelon', 'xigua'],
  '🍇': ['葡萄', 'grape', 'putao'],
  '🍓': ['草莓', 'strawberry', 'caomei'],
  '🍈': ['甜瓜', 'melon', 'tiangua'],
  '🍒': ['樱桃', 'cherries', 'yingtao'],
  '🍑': ['桃', 'peach', 'tao'],
  '🥭': ['芒果', 'mango', 'mangguo'],
  '🍍': ['菠萝', 'pineapple', 'boluo'],
  '🥥': ['椰子', 'coconut', 'yezi'],
  '🥝': ['猕猴桃', 'kiwi', 'mihoutao'],
  '🍅': ['番茄', '西红柿', 'tomato', 'fanqie'],
  '🥑': ['牛油果', 'avocado', 'niuyouguo'],
  '🥦': ['西兰花', 'broccoli', 'xilanhua'],
  '🌶️': ['辣椒', 'chili', 'pepper', 'lajiao'],
  '🌽': ['玉米', 'corn', 'yumi'],
  '🥕': ['胡萝卜', 'carrot', 'huluobo'],
  '🍠': ['地瓜', '红薯', 'sweet', 'potato', 'digua'],
  '☕': ['咖啡', 'coffee', 'kafei'],
  '🍵': ['茶', 'tea', 'cha'],
  '🧃': ['饮料', '果汁', 'juice', 'yinliao', 'guozhi'],
  '🥤': ['杯饮料', 'cup', 'straw', 'beizi'],
  '🧋': ['奶茶', '珍珠奶茶', 'boba', 'tea', 'naicha'],
  '🍺': ['啤酒', 'beer', 'pijiu'],
  '🍻': ['干杯', '啤酒', 'beers', 'cheers', 'ganbei'],
  '🍷': ['红酒', '葡萄酒', 'wine', 'hongjiu'],

  // ===== 运动 =====
  '⚽': ['足球', 'soccer', 'football', 'zuqiu'],
  '🏀': ['篮球', 'basketball', 'lanqiu'],
  '🏈': ['橄榄球', 'football', 'ganlanqiu'],
  '⚾': ['棒球', 'baseball', 'bangqiu'],
  '🎾': ['网球', 'tennis', 'wangqiu'],
  '🏐': ['排球', 'volleyball', 'paiqiu'],
  '🎱': ['台球', 'billiards', 'pool', 'taiqiu'],
  '🏓': ['乒乓球', 'ping', 'pong', 'pingpangqiu'],
  '🏸': ['羽毛球', 'badminton', 'yumaoqiu'],
  '🏒': ['冰球', 'hockey', 'ice', 'bingqiu'],
  '⛳': ['高尔夫', 'golf', 'gaoerfu'],
  '🏹': ['弓箭', 'bow', 'arrow', 'gongjian'],
  '🎣': ['钓鱼', 'fishing', 'diaoyu'],
  '🥊': ['拳击', 'boxing', 'quanji'],
  '🥋': ['武术', 'martial', 'arts', 'wushu'],
  '🎽': ['跑步衫', 'running', 'shirt', 'paobushan'],
  '🛹': ['滑板', 'skateboard', 'huaban'],
  '⛸️': ['滑冰', 'ice', 'skate', 'huabing'],
  '🥌': ['冰壶', 'curling', 'binghu'],
  '🎿': ['滑雪', 'ski', 'skiing', 'huaxue'],
  '🏂': ['单板滑雪', 'snowboard', 'danbanhuaxue'],
  '🏋️': ['举重', 'weight', 'lifter', 'juzhong'],
  '🤸': ['翻筋斗', 'cartwheel', 'fanjindou'],
  '⛹️': ['运球', 'bouncing', 'ball', 'yunqiu'],
  '🤺': ['击剑', 'fencing', 'jijian'],
  '🤾': ['手球', 'handball', 'shouqiu'],
  '🏇': ['赛马', 'horse', 'racing', 'saima'],
  '🧘': ['打坐', '冥想', 'meditation', 'yoga', 'dazuo'],
  '🏄': ['冲浪', 'surfing', 'chonglang'],
  '🏊': ['游泳', 'swimming', 'youyong'],

  // ===== 交通 =====
  '🚗': ['汽车', '车', 'car', 'qiche'],
  '🚕': ['出租车', '的士', 'taxi', 'cab', 'chuzuche'],
  '🚌': ['巴士', '公交车', 'bus', 'bashi'],
  '🏎️': ['赛车', 'racing', 'car', 'saiche'],
  '🚑': ['救护车', 'ambulance', 'jiuhuche'],
  '🚒': ['消防车', 'fire', 'engine', 'xiaofangche'],
  '🚐': ['面包车', 'minibus', 'van', 'mianbaoche'],
  '🚚': ['卡车', '货车', 'truck', 'kache'],
  '🏍️': ['摩托', 'motorcycle', 'moto', 'motuo'],
  '🛵': ['踏板车', 'scooter', 'tabanche'],
  '🚲': ['自行车', '单车', 'bike', 'zixingche'],
  '🛴': ['滑板车', 'scooter', 'huabanche'],
  '🚃': ['车厢', 'railway', 'car', 'chexiang'],
  '🚋': ['有轨电车', 'tram', 'youguidianche'],
  '🚄': ['高铁', '动车', 'high', 'speed', 'train', 'gaotie'],
  '🚅': ['新干线', 'bullet', 'train', 'xinganxian'],
  '🚂': ['蒸汽火车', 'locomotive', 'zhengqihuoche'],
  '✈️': ['飞机', 'airplane', 'plane', 'feiji'],
  '🛫': ['起飞', 'plane', 'takeoff', 'qifei'],
  '🛬': ['降落', 'plane', 'arrival', 'jiangluo'],
  '🚁': ['直升机', 'helicopter', 'zhishengji'],
  '🛸': ['飞碟', 'UFO', 'feidie'],
  '🚀': ['火箭', 'rocket', 'huojian'],
  '⛵': ['帆船', 'sailboat', 'fanchuan'],
  '🚢': ['轮船', '船', 'ship', 'lunchuan'],
  '🗺️': ['地图', 'world', 'map', 'ditu'],
  '🧭': ['指南针', 'compass', 'zhinanzhen'],
  '🏔️': ['雪山', 'mountain', 'snow', 'xueshan'],
  '⛰️': ['山', 'mountain', 'shan'],
  '🌋': ['火山', 'volcano', 'huoshan'],

  // ===== 建筑 =====
  '🏠': ['房子', '家', 'home', 'house', 'fangzi'],
  '🏡': ['花园房', 'house', 'garden', 'huayuanfang'],
  '🏢': ['办公楼', 'office', 'bangonglou'],
  '🏣': ['日本邮局', 'post', 'office', 'youju'],
  '🏤': ['邮局', 'post', 'office', 'youju'],
  '🏥': ['医院', 'hospital', 'yiyuan'],
  '🏦': ['银行', 'bank', 'yinhang'],
  '🏨': ['酒店', 'hotel', 'jiudian'],
  '🏩': ['爱情酒店', 'love', 'hotel', 'aiqing'],
  '🏪': ['便利店', 'convenience', 'store', 'bianlidian'],
  '🏫': ['学校', 'school', 'xuexiao'],
  '🏬': ['百货商场', 'department', 'store', 'baihuo'],
  '🏭': ['工厂', 'factory', 'gongchang'],
  '🏯': ['日本城', 'japanese', 'castle', 'ribenchen'],
  '🏰': ['城堡', 'castle', 'chengbao'],
  '💒': ['婚礼', 'marriage', 'heart', 'hunli'],
  '🗼': ['东京塔', 'tokyo', 'tower', 'dongjingtta'],
  '🗽': ['自由女神', 'liberty', 'statue', 'ziyounvshen'],
  '⛪': ['教堂', 'church', 'jiaotang'],
  '🕌': ['清真寺', 'mosque', 'qingzhensi'],
  '🛕': ['印度庙', 'hindu', 'temple', 'yindumiao'],
  '🕍': ['犹太庙', 'synagogue', 'youtaimiao'],
  '⛩️': ['鸟居', 'shrine', 'torii', 'niaoju'],
  '🕋': ['克尔白', 'kaaba', 'keerbai'],
  '🏟️': ['体育场', 'stadium', 'tiyuchang'],
  '🏛️': ['古典建筑', 'classical', 'building', 'gudian'],
  '🏗️': ['施工', 'crane', 'building', 'shigong'],

  // ===== 物品 =====
  '⌚': ['手表', 'watch', 'shoubiao'],
  '📱': ['手机', 'phone', 'mobile', 'shouji'],
  '💻': ['电脑', '笔记本', 'laptop', 'computer', 'diannao'],
  '⌨️': ['键盘', 'keyboard', 'jianpan'],
  '🖥️': ['台式电脑', 'desktop', 'taishi'],
  '🖨️': ['打印机', 'printer', 'dayinji'],
  '📷': ['相机', 'camera', 'xiangji'],
  '🎥': ['摄影机', 'movie', 'camera', 'sheyingji'],
  '📺': ['电视', 'TV', 'television', 'dianshi'],
  '📻': ['收音机', 'radio', 'shouyinji'],
  '💾': ['软盘', '保存', 'floppy', 'save', 'ruanpan'],
  '💿': ['光盘', 'CD', 'disk', 'guangpan'],
  '🔋': ['电池', 'battery', 'dianchi'],
  '🔌': ['插头', 'plug', '电源', 'chatou', 'dianyuan'],
  '💡': ['灯泡', 'idea', 'bulb', 'dengpao'],
  '🔦': ['手电筒', 'flashlight', 'shoudiantong'],
  '🕯️': ['蜡烛', 'candle', 'lazhu'],
  '📚': ['书', 'books', 'shu'],
  '📖': ['书', '本', 'open', 'book', 'shu'],
  '🔖': ['书签', 'bookmark', 'shuqian'],
  '📎': ['回形针', 'paperclip', 'huixingzhen'],
  '📌': ['图钉', 'pushpin', 'tudin'],
  '📍': ['圆图钉', 'round', 'pushpin', 'location', 'yuantudin', 'weizhi'],
  '✂️': ['剪刀', 'scissors', 'jiandao'],
  '✏️': ['铅笔', 'pencil', 'qianbi'],
  '📝': ['备忘录', '笔记', 'memo', 'note', 'biji'],
  '🔍': ['搜索', '放大镜', 'search', 'sousuo', 'fangdajing'],
  '🔒': ['锁', '上锁', 'lock', 'locked', 'suo'],
  '🔑': ['钥匙', 'key', 'yaoshi'],
  '🔧': ['扳手', 'wrench', 'banshou'],

  // ===== 符号 =====
  '🔴': ['红圆', 'red', 'circle', 'hongyuan', 'hong'],
  '🟠': ['橙圆', 'orange', 'circle', 'chengyuan', 'cheng'],
  '🟡': ['黄圆', 'yellow', 'circle', 'huangyuan', 'huang'],
  '🟢': ['绿圆', 'green', 'circle', 'lvyuan', 'lv'],
  '🔵': ['蓝圆', 'blue', 'circle', 'lanyuan', 'lan'],
  '🟣': ['紫圆', 'purple', 'circle', 'ziyuan', 'zi'],
  '🟤': ['棕圆', 'brown', 'circle', 'zongyuan', 'zong'],
  '⚫': ['黑圆', 'black', 'circle', 'heiyuan', 'hei'],
  '⚪': ['白圆', 'white', 'circle', 'baiyuan', 'bai'],
  '🔶': ['橙菱形', 'orange', 'diamond', 'chenglingsin'],
  '🔷': ['蓝菱形', 'blue', 'diamond', 'lanlingsin'],
  '🔸': ['小橙菱', 'orange', 'small', 'diamond'],
  '🔹': ['小蓝菱', 'blue', 'small', 'diamond'],
  '🔺': ['红三角', 'red', 'triangle', 'hongsanjiao'],
  '🔻': ['倒红三角', 'red', 'triangle', 'down', 'daohongsanjiao'],
  '💠': ['钻石装饰', 'diamond', 'decoration', 'zhuanshi'],
  '🔘': ['单选钮', 'radio', 'button', 'danxuanniu'],
  '✔️': ['勾', '对', 'check', 'mark', 'gou', 'dui'],
  '✖️': ['叉', '错', 'multiply', 'x', 'cha', 'cuo'],
  '❓': ['问号', '问', 'question', 'wenhao', 'wen'],
  '❗': ['感叹号', '叹号', 'exclamation', 'gantanhao'],
  '💯': ['满分', '一百', '100', 'hundred', 'manfen', 'yi'],
  '⚠️': ['警告', '注意', 'warning', 'caution', 'jinggao'],
  '♻️': ['回收', 'recycle', 'huisou'],
  '✅': ['勾', '对', 'check', 'done', 'gou', 'dui'],
  '❌': ['叉', '错', 'cross', 'no', 'cha', 'cuo'],
  '➕': ['加', 'plus', 'add', 'jia'],
  '➖': ['减', 'minus', 'subtract', 'jian'],
  '➗': ['除', 'divide', 'chu'],
  '♾️': ['无穷', 'infinity', 'wuqiong'],
};
